namespace PicoDI.Gen;

internal static partial class ServiceRegistrationSourceEmitter
{
    private const string AutoConfigurationFQN = "global::PicoDI.SvcContainerAutoConfiguration";

    public static void EmitSources(
        ServiceRegistrationGenerationPlan plan,
        Compilation compilation,
        SourceProductionContext context
    )
    {
        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = SanitizeIdentifier(assemblyName);

        // Only emit ServiceRegistrations when there are concrete (non-open-generic-only)
        // registrations. Libraries that only use Register(typeof(X<>), typeof(Y<>)) do not
        // need the Registration file, which references PicoDI.SvcContainerAutoConfiguration
        // and would force an unnecessary PicoDI dependency.
        if (!plan.Registrations.IsDefaultOrEmpty)
        {
            var source = BuildSource(
                plan.Registrations,
                compilation,
                assemblyName,
                safeAssemblyName
            );
            context.AddSource(
                $"PicoDI.ServiceRegistrations.{safeAssemblyName}.g.cs",
                SourceText.From(source, Encoding.UTF8)
            );
        }

        if (plan.OpenGenerics.IsDefaultOrEmpty)
            return;

        var metadataSource = OpenGenericMetadataContract.GenerateOpenGenericMetadata(
            plan.OpenGenerics.ToList()
        );
        context.AddSource(
            $"PicoDI.OpenGenericMetadata.{safeAssemblyName}.g.cs",
            SourceText.From(metadataSource, Encoding.UTF8)
        );
    }

    private static string BuildSource(
        ImmutableArray<ServiceRegistration> registrations,
        Compilation compilation,
        string assemblyName,
        string safeAssemblyName
    )
    {
        var sb = new StringBuilder();
        var safeClassName = $"GeneratedServiceRegistrations_{safeAssemblyName}";
        var generatedConfiguratorId = $"generated::{assemblyName}::{safeClassName}";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine();
        sb.AppendLine("namespace PicoDI.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Auto-generated service registrations with AOT-compatible factory methods."
        );
        sb.AppendLine("/// Optimized with inlined resolution chains for Transient services.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {safeClassName}");
        sb.AppendLine("{");

        AppendModuleInitializer(sb, generatedConfiguratorId);
        AppendConfigureGeneratedServicesMethod(sb);
        AppendGeneratedRegistrationCore(sb, registrations);
        AppendEnumerableRegistrations(sb, registrations);
        sb.AppendLine("    }");
        sb.AppendLine();

        var registrationLookup = registrations
            .GroupBy(r => r.ServiceTypeFullName)
            .ToDictionary(g => g.Key, g => g.Last());

        // Generated-code pruning: only emit Resolve methods for service types
        // actually referenced by other factories' dependency chains — not one
        // method per registration (the old behavior emitted ~90% unused methods
        // into every consumer assembly).
        var referencedResolvers = new HashSet<string>(StringComparer.Ordinal);
        foreach (var reg in registrations)
        {
            if (!reg.ConstructorParameters.IsEmpty)
                GenerateInlinedFactory(
                    reg,
                    registrationLookup,
                    [],
                    0,
                    "scope",
                    referencedResolvers
                );
        }
        GenerateTypedResolvers(sb, registrations, registrationLookup, referencedResolvers);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SanitizeIdentifier(string value)
    {
        return new string(
            value
                .Select(c => c == '.' ? '_' : c)
                .Where(c => char.IsLetterOrDigit(c) || c == '_')
                .ToArray()
        );
    }

    private static void AppendModuleInitializer(StringBuilder sb, string configuratorId)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Module initializer that registers the generated service configuration under a stable configurator identifier."
        );
        sb.AppendLine(
            "    /// This is called automatically when the assembly is loaded, before Main() runs."
        );
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void AutoRegisterConfigurator()");
        sb.AppendLine("    {");
        sb.AppendLine($"        {AutoConfigurationFQN}.RegisterConfigurator(");
        sb.AppendLine(
            $"            \"{EscapeStringLiteral(configuratorId)}\", static container => ConfigureGeneratedServicesCore(container));"
        );
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendConfigureGeneratedServicesMethod(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all scanned services with pre-compiled factory methods.");
        sb.AppendLine(
            "    /// This method is auto-generated by scanning Register* method calls in the codebase."
        );
        sb.AppendLine(
            "    /// Unlike constructor auto-configuration, this wrapper reapplies the generated registrations on every call."
        );
        sb.AppendLine(
            "    /// It marks generated configuration as applied for the container, but does not call Build() or route through TryApplyConfiguration()."
        );
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static global::PicoDI.Abs.ISvcContainer ConfigureGeneratedServices(this global::PicoDI.Abs.ISvcContainer container)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        ConfigureGeneratedServicesCore(container);");
        sb.AppendLine(
            $"        {AutoConfigurationFQN}.MarkGeneratedConfigurationApplied(container);"
        );
        sb.AppendLine("        return container;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string EscapeStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static void AppendGeneratedRegistrationCore(
        StringBuilder sb,
        ImmutableArray<ServiceRegistration> registrations
    )
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Core implementation that registers services without calling Build()."
        );
        sb.AppendLine(
            "    /// Used by Module Initializer to allow additional registrations after auto-configuration."
        );
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    private static void ConfigureGeneratedServicesCore(global::PicoDI.Abs.ISvcContainer container)"
        );
        sb.AppendLine("    {");

        var registrationLookup = registrations
            .GroupBy(r => r.ServiceTypeFullName)
            .ToDictionary(g => g.Key, g => g.Last());

        foreach (var reg in registrations)
        {
            AppendGeneratedRegistration(sb, reg, registrationLookup);
        }
    }

    private static void AppendGeneratedRegistration(
        StringBuilder sb,
        ServiceRegistration reg,
        Dictionary<string, ServiceRegistration> registrationLookup
    )
    {
        var lifetimeEnum = $"global::PicoDI.Abs.SvcLifetime.{reg.Lifetime}";
        sb.AppendLine("        container.Register(global::PicoDI.Abs.SvcDescriptor.Create(");
        sb.AppendLine($"            typeof({reg.ServiceTypeFullName}),");

        if (reg.ConstructorParameters.IsEmpty)
        {
            sb.AppendLine($"            static _ => new {reg.ImplementationTypeFullName}(),");
        }
        else
        {
            var factoryCode = GenerateInlinedFactory(reg, registrationLookup, [], 0);
            sb.AppendLine($"            static scope => {factoryCode},");
        }

        sb.AppendLine($"            {lifetimeEnum}));");
        sb.AppendLine();
    }

    private static void AppendEnumerableRegistrations(
        StringBuilder sb,
        ImmutableArray<ServiceRegistration> registrations
    )
    {
        sb.AppendLine("        // IEnumerable<T> registrations for AOT compatibility");

        foreach (
            var serviceTypeFullName in registrations
                .GroupBy(r => r.ServiceTypeFullName)
                .Select(g => g.Key)
        )
        {
            sb.AppendLine("        container.Register(global::PicoDI.Abs.SvcDescriptor.Create(");
            sb.AppendLine(
                $"            typeof(global::System.Collections.Generic.IEnumerable<{serviceTypeFullName}>),"
            );
            sb.AppendLine("            static scope => global::System.Linq.Enumerable.ToArray(");
            sb.AppendLine(
                $"                global::System.Linq.Enumerable.Cast<{serviceTypeFullName}>("
            );
            sb.AppendLine(
                $"                    scope.GetServices(typeof({serviceTypeFullName})))),"
            );
            sb.AppendLine("            global::PicoDI.Abs.SvcLifetime.Transient));");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Generates an inlined factory expression for the given registration.
    /// For Transient dependencies, recursively inlines the construction.
    /// For Singleton/Scoped dependencies, calls scope.GetService().
    /// </summary>
    private static string GenerateInlinedFactory(
        ServiceRegistration reg,
        Dictionary<string, ServiceRegistration> registrationLookup,
        HashSet<string> visitedTypes,
        int indentLevel,
        string scopeVarName = "scope",
        HashSet<string>? referencedResolvers = null
    )
    {
        if (reg.ConstructorParameters.IsEmpty)
            return $"new {reg.ImplementationTypeFullName}()";

        var paramExpressions = reg
            .ConstructorParameters.Select(paramTypeFullName =>
                GenerateParameterExpression(
                    paramTypeFullName,
                    registrationLookup,
                    visitedTypes,
                    indentLevel + 1,
                    scopeVarName,
                    referencedResolvers
                )
            )
            .ToList();

        if (paramExpressions.Count == 1)
            return $"new {reg.ImplementationTypeFullName}({paramExpressions[0]})";

        var sb = new StringBuilder();
        sb.Append($"new {reg.ImplementationTypeFullName}(");
        for (var i = 0; i < paramExpressions.Count; i++)
        {
            var comma = i < paramExpressions.Count - 1 ? "," : "";
            sb.Append(i is 0 ? paramExpressions[i] + comma : " " + paramExpressions[i] + comma);
        }
        sb.Append(")");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the expression for a constructor parameter.
    /// Inlines Transient dependencies, uses GetService for Singleton/Scoped.
    /// </summary>
    private static string GenerateParameterExpression(
        string paramTypeFullName,
        Dictionary<string, ServiceRegistration> registrationLookup,
        HashSet<string> visitedTypes,
        int indentLevel,
        string scopeVarName = "scope",
        HashSet<string>? referencedResolvers = null
    )
    {
        if (!registrationLookup.TryGetValue(paramTypeFullName, out var depReg))
            return $"({paramTypeFullName}){scopeVarName}.GetService(typeof({paramTypeFullName}))";

        var resolverName = GetResolverMethodName(paramTypeFullName);
        if (depReg.Lifetime != PicoDiNames.Transient)
        {
            referencedResolvers?.Add(resolverName);
            return $"Resolve.{resolverName}({scopeVarName})";
        }

        if (visitedTypes.Contains(paramTypeFullName))
        {
            referencedResolvers?.Add(resolverName);
            return $"Resolve.{resolverName}({scopeVarName})";
        }

        var newVisited = new HashSet<string>(visitedTypes) { paramTypeFullName };
        return GenerateInlinedFactory(
            depReg,
            registrationLookup,
            newVisited,
            indentLevel,
            scopeVarName,
            referencedResolvers
        );
    }
}
