<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <PackageId>PicoMediator.Abs</PackageId>
    <Description>Abstractions for PicoMediator — compile-time command/event dispatch</Description>
    <PackageTags>PicoHex;Mediator;Messaging;Abstractions</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\PicoMediator.Gen\PicoMediator.Gen.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
      PrivateAssets="all"
    />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="..\PicoMediator.Gen\bin\$(Configuration)\netstandard2.0\PicoMediator.Gen.dll"
      Pack="true"
      PackagePath="analyzers/dotnet/cs"
      Visible="false"
    />
    <None
      Include="buildTransitive\PicoMediator.Abs.props"
      Pack="true"
      PackagePath="buildTransitive\PicoMediator.Abs.props"
      Visible="false"
    />
  </ItemGroup>
</Project>
