<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <PackageId>PicoLog.Abs</PackageId>
    <Description>Abstractions for PicoLog structured logging (ILogger, ILogSink, LogLevel, LogEntry).</Description>
    <PackageTags>PicoHex;Logging;AOT;Logging Injection;Abstractions</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\PicoLog.Gen\PicoLog.Gen.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
      PrivateAssets="all"
    />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="..\PicoLog.Genin\$(Configuration)
etstandard2.0\PicoLog.Gen.dll"
      Pack="true"
      PackagePath="analyzers/dotnet/cs"
      Visible="false"
    />
    <None
      Include="buildTransitive\PicoLog.Abs.props"
      Pack="true"
      PackagePath="buildTransitive\PicoLog.Abs.props"
      Visible="false"
    />
  </ItemGroup>

</Project>
