namespace PicoCfg.Gen;

// Renders generated registration and binding code from validated models.
public sealed partial class PicoCfgBindGenerator
{
    private static string Render(
        IReadOnlyList<TargetModel> targets,
        ISet<ITypeSymbol> referencedNestedTypes
    )
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace PicoCfg;");
        sb.AppendLine();
        sb.AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sb.AppendLine("internal static class PicoCfgBindGeneratedRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        for (var i = 0; i < targets.Count; i++)
        {
            var target = targets[i];
            var typeName = target.TargetType.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat
            );
            var bindDelegateType =
                "global::System.Func<global::PicoCfg.Abs.ICfg, string?, " + typeName + ">";
            var tryBindDelegateType =
                "global::PicoCfg.PicoCfgGeneratedTryBindDelegate<" + typeName + ">";
            var bindIntoDelegateType =
                "global::PicoCfg.PicoCfgGeneratedBindIntoDelegate<" + typeName + ">";
            var needsBind = NeedsBindMethod(target, referencedNestedTypes);
            var needsTryBind = NeedsTryBindMethod(target);
            var needsBindInto = NeedsBindIntoMethod(target, needsBind);
            var hasCtor = needsBind ? "(" + bindDelegateType + ")Bind_" + i : "null";
            var hasTryBind = needsTryBind ? "(" + tryBindDelegateType + ")TryBind_" + i : "null";
            var hasBindInto = needsBindInto
                ? "(" + bindIntoDelegateType + ")BindInto_" + i
                : "null";

            sb.Append("        global::PicoCfg.CfgBindRuntime.Register<")
                .Append(typeName)
                .AppendLine(">(");
            sb.AppendLine(
                "            contractVersion: global::PicoCfg.CfgBindRuntime.ContractVersion,"
            );
            sb.Append("            bind: ").Append(hasCtor).AppendLine(",");
            sb.Append("            tryBind: ").Append(hasTryBind).AppendLine(",");
            sb.Append("            bindInto: ").Append(hasBindInto).AppendLine(");");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        for (var i = 0; i < targets.Count; i++)
            AppendTargetMethods(sb, targets[i], i, referencedNestedTypes);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool NeedsBindMethod(
        TargetModel target,
        ISet<ITypeSymbol> referencedNestedTypes
    ) =>
        CanConstruct(target)
        && (
            target.Operations.HasFlag(BindOperation.Bind)
            || referencedNestedTypes.Contains(target.TargetType)
        );

    private static bool NeedsTryBindMethod(TargetModel target) =>
        CanConstruct(target) && target.Operations.HasFlag(BindOperation.TryBind);

    private static bool NeedsBindIntoMethod(TargetModel target, bool needsBind)
    {
        if (target.Operations.HasFlag(BindOperation.BindInto))
            return true;

        // The parameterless-constructor Bind_ path delegates to BindInto_, so an
        // emitted Bind_ needs its BindInto_ counterpart. The init-only and
        // primary-constructor paths construct inline and never call BindInto_.
        return needsBind
            && target.HasPublicParameterlessConstructor
            && !target.Properties.Any(static p => p.RequiresInitializerSyntax);
    }

    private static bool NeedsTryBindIntoMethod(TargetModel target) =>
        // Only the parameterless-constructor TryBind_ path delegates to
        // TryBindInto_; the init-only and primary-constructor paths are inline.
        target.Operations.HasFlag(BindOperation.TryBind)
        && target.HasPublicParameterlessConstructor
        && !target.Properties.Any(static p => p.RequiresInitializerSyntax);

    private static void AppendTargetMethods(
        StringBuilder sb,
        TargetModel target,
        int index,
        ISet<ITypeSymbol> referencedNestedTypes
    )
    {
        var typeName = target.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var hasInitOnly = target.Properties.Any(static p => p.RequiresInitializerSyntax);
        var needsBind = NeedsBindMethod(target, referencedNestedTypes);
        var needsTryBind = NeedsTryBindMethod(target);
        var needsBindInto = NeedsBindIntoMethod(target, needsBind);
        var needsTryBindInto = NeedsTryBindIntoMethod(target);

        if (target.HasPublicParameterlessConstructor || target.HasPrimaryConstructor)
        {
            if (
                !target.HasPublicParameterlessConstructor
                && target.PrimaryConstructor is { } primaryCtor
            )
            {
                // Positional records (primary constructor, no public parameterless
                // constructor) construct via their primary constructor, mapping
                // parameters to properties by name.
                if (needsBind)
                    AppendBindMethodWithPrimaryCtor(sb, target, primaryCtor, index, typeName);
                if (needsTryBind)
                    AppendTryBindMethodWithPrimaryCtor(sb, target, primaryCtor, index, typeName);
            }
            else if (hasInitOnly)
            {
                if (needsBind)
                    AppendBindMethodWithInitOnly(sb, target, index, typeName);
                if (needsTryBind)
                    AppendTryBindMethodWithInitOnly(sb, target, index, typeName);
            }
            else
            {
                if (needsBind)
                {
                    sb.Append("    private static ")
                        .Append(typeName)
                        .Append(" Bind_")
                        .Append(index)
                        .AppendLine("(global::PicoCfg.Abs.ICfg cfg, string? section)");
                    sb.AppendLine("    {");
                    sb.Append("        var instance = new ").Append(typeName).AppendLine("();");
                    sb.Append("        BindInto_")
                        .Append(index)
                        .AppendLine("(cfg, section, instance);");
                    sb.AppendLine("        return instance;");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }

                if (needsTryBind)
                {
                    sb.Append("    private static bool TryBind_")
                        .Append(index)
                        .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, out ")
                        .Append(typeName)
                        .AppendLine(" value)");
                    sb.AppendLine("    {");
                    sb.Append("        var instance = new ").Append(typeName).AppendLine("();");
                    sb.Append("        if (!TryBindInto_")
                        .Append(index)
                        .AppendLine("(cfg, section, instance))");
                    sb.AppendLine("        {");
                    sb.AppendLine("            value = default!;");
                    sb.AppendLine("            return false;");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        value = instance;");
                    sb.AppendLine("        return true;");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }
        }

        if (needsBindInto)
        {
            sb.Append("    private static void BindInto_")
                .Append(index)
                .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, ")
                .Append(typeName)
                .AppendLine(" instance)");
            sb.AppendLine("    {");
            foreach (var property in target.Properties)
            {
                if (property.RequiresInitializerSyntax)
                    continue;
                if (IsUnresolvedNestedProperty(property))
                    continue;
                AppendBindProperty(sb, target, property, throwOnFailure: true);
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        if (needsTryBindInto)
        {
            sb.Append("    private static bool TryBindInto_")
                .Append(index)
                .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, ")
                .Append(typeName)
                .AppendLine(" instance)");
            sb.AppendLine("    {");
            sb.AppendLine("        var any = false;");
            foreach (var property in target.Properties)
            {
                if (property.RequiresInitializerSyntax)
                    continue;
                if (IsUnresolvedNestedProperty(property))
                    continue;
                AppendBindProperty(sb, target, property, throwOnFailure: false);
            }
            sb.AppendLine("        return any;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private static void AppendBindMethodWithInitOnly(
        StringBuilder sb,
        TargetModel target,
        int index,
        string typeName
    )
    {
        sb.Append("    private static ")
            .Append(typeName)
            .Append(" Bind_")
            .Append(index)
            .AppendLine("(global::PicoCfg.Abs.ICfg cfg, string? section)");
        sb.AppendLine("    {");

        AppendInlinePropertyValues(sb, target, throwOnFailure: true, hasAnyVar: false);

        sb.Append("        return ");
        AppendConstructionCore(sb, target, typeName, ctorArgs: null, consumedProperties: null);
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits <c>Bind_&lt;index&gt;</c> for a positional record: every inline property
    /// value is resolved first, then the record is constructed through its primary
    /// constructor (parameters map to properties by name) and any remaining
    /// non-constructor properties are assigned via an object initializer.
    /// </summary>
    private static void AppendBindMethodWithPrimaryCtor(
        StringBuilder sb,
        TargetModel target,
        IMethodSymbol primaryCtor,
        int index,
        string typeName
    )
    {
        sb.Append("    private static ")
            .Append(typeName)
            .Append(" Bind_")
            .Append(index)
            .AppendLine("(global::PicoCfg.Abs.ICfg cfg, string? section)");
        sb.AppendLine("    {");

        AppendInlinePropertyValues(sb, target, throwOnFailure: true, hasAnyVar: false);

        var ctorArgs = BuildPrimaryCtorArguments(target, primaryCtor);
        var consumed = GetPrimaryCtorConsumedProperties(target, primaryCtor);
        sb.Append("        return ");
        AppendConstructionCore(sb, target, typeName, ctorArgs, consumed);
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendTryBindMethodWithPrimaryCtor(
        StringBuilder sb,
        TargetModel target,
        IMethodSymbol primaryCtor,
        int index,
        string typeName
    )
    {
        sb.Append("    private static bool TryBind_")
            .Append(index)
            .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, out ")
            .Append(typeName)
            .AppendLine(" value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var any = false;");
        sb.Append("        value = default!;").AppendLine();
        sb.AppendLine();

        AppendInlinePropertyValues(sb, target, throwOnFailure: false, hasAnyVar: true);

        sb.AppendLine();
        var ctorArgs = BuildPrimaryCtorArguments(target, primaryCtor);
        var consumed = GetPrimaryCtorConsumedProperties(target, primaryCtor);
        sb.Append("        value = ");
        AppendConstructionCore(sb, target, typeName, ctorArgs, consumed);
        sb.AppendLine("        return any;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Builds the constructor argument expressions for a positional record's
    /// primary constructor. Each parameter maps to its same-named bindable
    /// property's inline value variable; parameters without a bindable property
    /// fall back to <c>default</c>.
    /// </summary>
    private static List<string>? BuildPrimaryCtorArguments(
        TargetModel target,
        IMethodSymbol primaryCtor
    )
    {
        if (primaryCtor.Parameters.Length == 0)
            return null;

        var args = new List<string>(primaryCtor.Parameters.Length);
        foreach (var parameter in primaryCtor.Parameters)
        {
            var property = FindBindableProperty(target, parameter.Name);
            var canPass = property is not null && !IsUnresolvedNestedProperty(property);
            args.Add(
                canPass ? "__value_" + property!.Name
                : parameter.Type.IsReferenceType ? "default!"
                : "default"
            );
        }
        return args;
    }

    /// <summary>
    /// Names of the bindable properties consumed by the primary constructor's
    /// parameters — these are passed positionally and must not be repeated in
    /// the object initializer.
    /// </summary>
    private static HashSet<string> GetPrimaryCtorConsumedProperties(
        TargetModel target,
        IMethodSymbol primaryCtor
    )
    {
        var consumed = new HashSet<string>(StringComparer.Ordinal);
        foreach (var parameter in primaryCtor.Parameters)
        {
            if (FindBindableProperty(target, parameter.Name) is { } property)
                consumed.Add(property.Name);
        }
        return consumed;
    }

    private static PropertyModel? FindBindableProperty(TargetModel target, string name)
    {
        foreach (var property in target.Properties)
        {
            if (property.Name == name)
                return property;
        }

        foreach (var property in target.Properties)
        {
            if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
                return property;
        }

        return null;
    }

    /// <summary>
    /// Emits <c>new TypeName(...) { ... };</c>. When <paramref name="ctorArgs"/>
    /// is non-null the type is constructed with positional arguments and the
    /// initializer is limited to properties not consumed by those arguments.
    /// The caller prefixes the assignment target (<c>return </c> or <c>value = </c>).
    /// </summary>
    private static void AppendConstructionCore(
        StringBuilder sb,
        TargetModel target,
        string typeName,
        List<string>? ctorArgs,
        HashSet<string>? consumedProperties
    )
    {
        if (ctorArgs is { Count: > 0 })
        {
            sb.Append("new ")
                .Append(typeName)
                .Append('(')
                .Append(string.Join(", ", ctorArgs))
                .AppendLine(")");
        }
        else
        {
            sb.Append("new ").Append(typeName).AppendLine();
        }

        sb.AppendLine("        {");
        for (var i = 0; i < target.Properties.Length; i++)
        {
            var property = target.Properties[i];
            if (IsUnresolvedNestedProperty(property))
                continue;
            if (consumedProperties is not null && consumedProperties.Contains(property.Name))
                continue;
            var separator = i < target.Properties.Length - 1 ? "," : "";
            sb.Append("            ")
                .Append(property.Name)
                .Append(" = __value_")
                .Append(property.Name)
                .Append(separator)
                .AppendLine();
        }
        sb.AppendLine("        };");
    }

    private static void AppendTryBindMethodWithInitOnly(
        StringBuilder sb,
        TargetModel target,
        int index,
        string typeName
    )
    {
        sb.Append("    private static bool TryBind_")
            .Append(index)
            .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, out ")
            .Append(typeName)
            .AppendLine(" value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var any = false;");
        sb.Append("        value = default!;").AppendLine();
        sb.AppendLine();

        AppendInlinePropertyValues(sb, target, throwOnFailure: false, hasAnyVar: true);

        sb.AppendLine();
        sb.Append("        value = ");
        AppendConstructionCore(sb, target, typeName, ctorArgs: null, consumedProperties: null);
        sb.AppendLine("        return any;");
        ;
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Shared scalar property binding used by both the BindInto path
    /// (<see cref="AppendBindProperty"/>) and the init-only inline path
    /// (<see cref="AppendInlinePropertyValues"/>).
    /// </summary>
    /// <param name="assignmentLeft">
    /// Left-hand side of the assignment, e.g. "instance.Name" (BindInto)
    /// or "__value_Name" (inline).
    /// </param>
    /// <param name="emitAnyVar">
    /// Whether to emit <c>any = true;</c> in the try-bind path.
    /// </param>
    /// <param name="valueTypeDeclaration">
    /// Optional type name for a local variable declaration emitted before
    /// the lookup.  <see langword="null" /> for the BindInto path.
    /// </param>
    /// <param name="isRequired">
    /// Whether to emit the <c>else { default }</c> fallback for required
    /// properties (BindInto path only).
    /// </param>
    /// <param name="appendTrailingLine">
    /// Whether to append an empty line after the closing brace.
    /// </param>
    private static void AppendScalarBindingCore(
        StringBuilder sb,
        TargetModel target,
        PropertyModel property,
        bool throwOnFailure,
        string assignmentLeft,
        bool emitAnyVar,
        string? valueTypeDeclaration,
        bool isRequired,
        bool appendTrailingLine
    )
    {
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var targetDisplay = SymbolDisplay.FormatLiteral(
            property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
            true
        );
        var memberDisplay = SymbolDisplay.FormatLiteral(
            target.TargetType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                + "."
                + property.Name,
            true
        );
        var rawName = "__raw_" + property.Name;
        var pathName = "__path_" + property.Name;
        var valueName = "__value_" + property.Name;
        // In the inline (init-only) path the accumulator is pre-declared with the
        // property's nullable-aware type; the parse must target a separate local so
        // the emitted code never assigns a variable to itself (CS1717) and never
        // passes a nullable accumulator as the 'out' target of a non-nullable
        // parse method (CS1503).
        var parseName = valueTypeDeclaration is null ? valueName : "__parsed_" + property.Name;

        if (valueTypeDeclaration is { } vt)
        {
            var valueType =
                property.ScalarKind == ScalarKind.String ? property.Type
                : property.IsNullable ? property.Type
                : property.UnderlyingType;
            var defaultValue = valueType.IsReferenceType ? "default!" : "default";

            sb.Append("        ")
                .Append(vt)
                .Append(" ")
                .Append(assignmentLeft)
                .Append(" = ")
                .Append(defaultValue)
                .AppendLine(";");
        }

        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        if (global::PicoCfg.CfgBindRuntime.TryGetValueIgnoreCase(cfg, section, ")
            .Append(propertyPathLiteral)
            .Append(", out var ")
            .Append(rawName)
            .AppendLine("))");
        sb.AppendLine("        {");

        if (emitAnyVar)
            sb.AppendLine("            any = true;");

        if (property.ScalarKind == ScalarKind.String)
        {
            sb.Append("            ")
                .Append(assignmentLeft)
                .Append(" = ")
                .Append(rawName)
                .AppendLine("!;");
        }
        else if (property.IsNullable)
        {
            sb.Append("            if (string.IsNullOrEmpty(").Append(rawName).AppendLine("))");
            sb.AppendLine("            {");
            sb.Append("                ").Append(assignmentLeft).AppendLine(" = null;");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            AppendParseBlock(
                sb,
                property,
                rawName,
                parseName,
                pathName,
                targetDisplay,
                memberDisplay,
                throwOnFailure,
                indent: "                "
            );
            sb.Append("                ")
                .Append(assignmentLeft)
                .Append(" = ")
                .Append(parseName)
                .AppendLine(";");
            sb.AppendLine("            }");
        }
        else
        {
            AppendParseBlock(
                sb,
                property,
                rawName,
                parseName,
                pathName,
                targetDisplay,
                memberDisplay,
                throwOnFailure,
                indent: "            "
            );
            sb.Append("            ")
                .Append(assignmentLeft)
                .Append(" = ")
                .Append(parseName)
                .AppendLine(";");
        }

        sb.AppendLine("        }");

        if (isRequired)
        {
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.Append("            ").Append(assignmentLeft).Append(" = ");
            sb.Append(property.Type.IsReferenceType ? "default!" : "default");
            sb.AppendLine(";");
            sb.AppendLine("        }");
        }

        if (appendTrailingLine)
            sb.AppendLine();
    }

    /// <summary>
    /// True when a nested property's target type never made it into the final
    /// sorted model set (truncated below the nesting depth limit or excluded by
    /// analysis diagnostics) — its <c>Bind_&lt;N&gt;</c> method does not exist, so
    /// the property must be skipped rather than referencing <c>Bind_-1</c>.
    /// </summary>
    private static bool IsUnresolvedNestedProperty(PropertyModel property) =>
        property.ScalarKind == ScalarKind.Nested && property.NestedModelIndex < 0;

    private static void AppendInlinePropertyValues(
        StringBuilder sb,
        TargetModel target,
        bool throwOnFailure,
        bool hasAnyVar
    )
    {
        foreach (var property in target.Properties)
        {
            if (property.ScalarKind == ScalarKind.Nested)
            {
                if (property.NestedModelIndex < 0)
                    continue;
                AppendNestedInlineValue(sb, property, hasAnyVar);
                continue;
            }

            if (
                property.ScalarKind
                is ScalarKind.Collection_List
                    or ScalarKind.Collection_Array
                    or ScalarKind.Collection_Dictionary
            )
            {
                AppendCollectionInlineValue(sb, property, hasAnyVar, throwOnFailure);
                continue;
            }

            AppendScalarBindingCore(
                sb,
                target,
                property,
                throwOnFailure,
                assignmentLeft: "__value_" + property.Name,
                emitAnyVar: hasAnyVar,
                valueTypeDeclaration: GetValueTypeName(property),
                isRequired: false,
                appendTrailingLine: true
            );
        }
    }

    private static void AppendBindProperty(
        StringBuilder sb,
        TargetModel target,
        PropertyModel property,
        bool throwOnFailure
    )
    {
        if (property.ScalarKind == ScalarKind.Nested)
        {
            AppendNestedBindProperty(sb, property, throwOnFailure);
            return;
        }

        if (
            property.ScalarKind
            is ScalarKind.Collection_List
                or ScalarKind.Collection_Array
                or ScalarKind.Collection_Dictionary
        )
        {
            AppendCollectionBindProperty(sb, property, throwOnFailure);
            return;
        }

        AppendScalarBindingCore(
            sb,
            target,
            property,
            throwOnFailure,
            assignmentLeft: "instance." + property.Name,
            emitAnyVar: !throwOnFailure,
            valueTypeDeclaration: null,
            isRequired: property.IsRequired,
            appendTrailingLine: false
        );
    }

    private static string GetValueTypeName(PropertyModel property)
    {
        return property.ScalarKind == ScalarKind.String ? "string"
            : property.IsNullable
                ? property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : property.UnderlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static void AppendNestedBindProperty(
        StringBuilder sb,
        PropertyModel property,
        bool throwOnFailure
    )
    {
        var pathName = "__path_" + property.Name;
        var sectionName = "__section_" + property.Name;
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);

        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(sectionName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(cfg, ")
            .Append(pathName)
            .AppendLine(");");
        sb.Append("        instance.")
            .Append(property.Name)
            .Append(" = Bind_")
            .Append(property.NestedModelIndex)
            .Append("(")
            .Append(sectionName)
            .AppendLine(", null);");
        if (!throwOnFailure)
            sb.AppendLine("        any = true;");
    }

    private static void AppendNestedInlineValue(
        StringBuilder sb,
        PropertyModel property,
        bool hasAnyVar
    )
    {
        var valueName = "__value_" + property.Name;
        var pathName = "__path_" + property.Name;
        var sectionName = "__section_" + property.Name;
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var valueTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append("        ")
            .Append(valueTypeName)
            .Append(" ")
            .Append(valueName)
            .AppendLine(" = default!;");
        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(sectionName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(cfg, ")
            .Append(pathName)
            .AppendLine(");");
        sb.Append("        ")
            .Append(valueName)
            .Append(" = Bind_")
            .Append(property.NestedModelIndex)
            .Append("(")
            .Append(sectionName)
            .AppendLine(", null);");
        if (hasAnyVar)
            sb.AppendLine("        any = true;");
        sb.AppendLine();
    }

    /// <summary>
    /// Shared collection binding loop used by both the BindInto path
    /// (<see cref="AppendCollectionBindProperty"/>) and the init-only
    /// inline path (<see cref="AppendCollectionInlineValue"/>).
    /// </summary>
    /// <param name="assignmentLeft">
    /// Left-hand side of the final assignment, e.g. "instance.Providers"
    /// (BindInto) or "__value_Providers" (inline).
    /// </param>
    /// <param name="emitAnyVar">
    /// Whether to emit <c>any = true;</c> after the loop.
    /// </param>
    /// <param name="valueTypeDeclaration">
    /// Optional fully-qualified type name for a local variable declaration
    /// emitted before the loop.  <see langword="null" /> for the BindInto
    /// path; non-null for the init-only inline path.
    /// </param>
    /// <param name="appendTrailingLine">
    /// Whether to append an empty line after the closing brace.
    /// </param>
    private static void AppendCollectionBindingCore(
        StringBuilder sb,
        PropertyModel property,
        bool throwOnFailure,
        string assignmentLeft,
        bool emitAnyVar,
        string? valueTypeDeclaration,
        bool appendTrailingLine
    )
    {
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var pathName = "__path_" + property.Name;
        var sectionName = "__section_" + property.Name;
        var isDictionary = property.ScalarKind == ScalarKind.Collection_Dictionary;
        var accName = isDictionary ? "__dict_" + property.Name : "__list_" + property.Name;

        string accTypeFqn;
        if (
            property.ScalarKind == ScalarKind.Collection_Array
            && property.ElementBinding is { } arrBinding
        )
        {
            var arrElemFqn = arrBinding.Type.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat
            );
            accTypeFqn = "global::System.Collections.Generic.List<" + arrElemFqn + ">";
        }
        else if (
            property.ScalarKind == ScalarKind.Collection_List
            && property.Type is INamedTypeSymbol { TypeKind: TypeKind.Interface }
            && property.ElementBinding is { } ifaceBinding
        )
        {
            // Read-only collection interfaces (IReadOnlyList<T>, IReadOnlyCollection<T>,
            // IEnumerable<T>) cannot be instantiated — accumulate into List<T> and assign.
            var ifaceElemFqn = ifaceBinding.Type.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat
            );
            accTypeFqn = "global::System.Collections.Generic.List<" + ifaceElemFqn + ">";
        }
        else
        {
            accTypeFqn = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        if (valueTypeDeclaration is { } vt)
        {
            sb.Append("        ")
                .Append(vt)
                .Append(" ")
                .Append(assignmentLeft)
                .AppendLine(" = default!;");
        }

        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(sectionName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(cfg, ")
            .Append(pathName)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(accName)
            .Append(" = new ")
            .Append(accTypeFqn)
            .AppendLine("();");

        AppendCollectionLoop(
            sb,
            property,
            property.ElementBinding,
            sectionName,
            accName,
            isDictionary,
            throwOnFailure,
            pathName,
            depth: 0
        );

        if (emitAnyVar)
            sb.AppendLine("        any = true;");

        if (property.ScalarKind == ScalarKind.Collection_Array)
        {
            sb.Append("        ")
                .Append(assignmentLeft)
                .Append(" = ")
                .Append(accName)
                .AppendLine(".ToArray();");
        }
        else
        {
            sb.Append("        ")
                .Append(assignmentLeft)
                .Append(" = ")
                .Append(accName)
                .AppendLine(";");
        }

        if (appendTrailingLine)
            sb.AppendLine();
    }

    /// <summary>
    /// Renders one collection iteration loop (list or dictionary) over a scoped
    /// view. Element binding recurses through <see cref="AppendElementBinding"/>
    /// so nested collections (e.g. Dictionary&lt;string, Dictionary&lt;string, string&gt;&gt;)
    /// bind natively. Depth 0 uses the historical variable names; deeper levels
    /// append a numeric suffix to keep every local unique.
    /// </summary>
    private static void AppendCollectionLoop(
        StringBuilder sb,
        PropertyModel property,
        ElementBindingModel? element,
        string sectionVar,
        string accVar,
        bool isDictionary,
        bool throwOnFailure,
        string pathPrefix,
        int depth
    )
    {
        var iVar = depth == 0 ? "__i" : $"__i_{depth}";
        var rawVar =
            depth == 0
                ? isDictionary
                    ? "__rawKey"
                    : "__raw"
                : isDictionary
                    ? $"__rawKey_{depth}"
                    : $"__raw_{depth}";

        sb.Append("        for (var ")
            .Append(iVar)
            .Append(" = 0; ; ")
            .Append(iVar)
            .AppendLine("++)");
        sb.AppendLine("        {");

        if (isDictionary)
        {
            sb.Append("            if (!")
                .Append(sectionVar)
                .AppendLine(
                    ".TryGetValue("
                        + iVar
                        + ".ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \":Key\", out var "
                        + rawVar
                        + "))"
                );
            sb.AppendLine("                break;");
        }
        else
        {
            var needsPrefixSentinel =
                element is not null
                && element.Kind
                    is ScalarKind.Nested
                        or ScalarKind.Collection_List
                        or ScalarKind.Collection_Array
                        or ScalarKind.Collection_Dictionary;
            var leafCheck =
                "            if (!"
                + sectionVar
                + ".TryGetValue("
                + iVar
                + ".ToString(global::System.Globalization.CultureInfo.InvariantCulture), out var "
                + rawVar
                + "))";
            if (needsPrefixSentinel)
            {
                // The element stores its data at Section:N:... — the leaf Section:N may
                // not exist, so fall back to a prefix check before breaking.
                sb.AppendLine(leafCheck);
                sb.AppendLine("            {");
                sb.Append("                if (!global::PicoCfg.CfgBindRuntime.HasKeyPrefix(")
                    .Append(sectionVar)
                    .Append(", ")
                    .Append(iVar)
                    .AppendLine(
                        ".ToString(global::System.Globalization.CultureInfo.InvariantCulture)))"
                    );
                sb.AppendLine("                    break;");
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine(leafCheck);
                sb.AppendLine("                break;");
            }
        }

        AppendElementBinding(
            sb,
            property,
            element,
            sectionVar,
            iVar,
            rawVar,
            accVar,
            isDictionary,
            throwOnFailure,
            pathPrefix,
            depth
        );

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Renders the binding of one collection element into <paramref name="accVar"/>:
    /// nested class → delegate bind; nested collection → recursive loop; scalar →
    /// parse (dictionary values first read the ":Value" slot).
    /// </summary>
    private static void AppendElementBinding(
        StringBuilder sb,
        PropertyModel property,
        ElementBindingModel? element,
        string sectionVar,
        string iVar,
        string rawVar,
        string accVar,
        bool parentIsDictionary,
        bool throwOnFailure,
        string pathPrefix,
        int depth
    )
    {
        if (element is null)
            return;

        var elementSuffix = parentIsDictionary ? " + \":Value\"" : "";
        var elementIndexExpr =
            iVar
            + ".ToString(global::System.Globalization.CultureInfo.InvariantCulture)"
            + elementSuffix;

        if (element.Kind == ScalarKind.Nested)
        {
            if (element.NestedModelIndex < 0)
                return;
            var elemVar = depth == 0 ? "__elem_" + property.Name : $"__elem_{depth}";
            sb.Append("            var ")
                .Append(elemVar)
                .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(")
                .Append(sectionVar)
                .Append(", ")
                .Append(elementIndexExpr)
                .AppendLine(");");
            if (parentIsDictionary)
            {
                sb.Append("            ")
                    .Append(accVar)
                    .AppendLine(
                        "["
                            + rawVar
                            + "!] = Bind_"
                            + element.NestedModelIndex
                            + "("
                            + elemVar
                            + ", null);"
                    );
            }
            else
            {
                sb.Append("            ")
                    .Append(accVar)
                    .AppendLine(
                        ".Add(Bind_" + element.NestedModelIndex + "(" + elemVar + ", null));"
                    );
            }
            return;
        }

        if (
            element.Kind
            is ScalarKind.Collection_List
                or ScalarKind.Collection_Array
                or ScalarKind.Collection_Dictionary
        )
        {
            var nextDepth = depth + 1;
            var nestedAccVar = $"__nested_{nextDepth}";
            var nestedSectionVar = $"__section_{nextDepth}";
            var nestedIsDictionary = element.Kind == ScalarKind.Collection_Dictionary;

            sb.Append("            var ")
                .Append(nestedAccVar)
                .Append(" = new ")
                .Append(GetAccumulatorTypeFqn(element))
                .AppendLine("();");
            sb.Append("            var ")
                .Append(nestedSectionVar)
                .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(")
                .Append(sectionVar)
                .Append(", ")
                .Append(elementIndexExpr)
                .AppendLine(");");

            var childPathExpr =
                pathPrefix
                + " + \":\" + "
                + iVar
                + ".ToString(global::System.Globalization.CultureInfo.InvariantCulture)"
                + elementSuffix;

            AppendCollectionLoop(
                sb,
                property,
                element.Element,
                nestedSectionVar,
                nestedAccVar,
                nestedIsDictionary,
                throwOnFailure,
                childPathExpr,
                nextDepth
            );

            var nestedValueExpr =
                element.Kind == ScalarKind.Collection_Array
                    ? nestedAccVar + ".ToArray()"
                    : nestedAccVar;
            if (parentIsDictionary)
            {
                sb.Append("            ")
                    .Append(accVar)
                    .AppendLine("[" + rawVar + "!] = " + nestedValueExpr + ";");
            }
            else
            {
                sb.Append("            ")
                    .Append(accVar)
                    .AppendLine(".Add(" + nestedValueExpr + ");");
            }
            return;
        }

        // Scalar element.
        var parsedVar = depth == 0 ? "__parsed" : $"__parsed_{depth}";
        if (parentIsDictionary)
        {
            var rawValueVar = depth == 0 ? "__rawValue" : $"__rawValue_{depth}";
            sb.Append("            if (!")
                .Append(sectionVar)
                .AppendLine(
                    ".TryGetValue("
                        + iVar
                        + ".ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \":Value\", out var "
                        + rawValueVar
                        + "))"
                );
            sb.AppendLine("                break;");

            if (element.Kind == ScalarKind.String)
            {
                sb.Append("            ")
                    .Append(accVar)
                    .AppendLine("[" + rawVar + "!] = " + rawValueVar + "!;");
            }
            else
            {
                AppendScalarElementParse(
                    sb,
                    property,
                    element,
                    rawValueVar,
                    parsedVar,
                    accVar,
                    parentIsDictionary: true,
                    rawVar,
                    throwOnFailure,
                    pathPrefix,
                    iVar
                );
            }
        }
        else if (element.Kind == ScalarKind.String)
        {
            sb.Append("            ").Append(accVar).AppendLine(".Add(" + rawVar + "!);");
        }
        else
        {
            AppendScalarElementParse(
                sb,
                property,
                element,
                rawVar,
                parsedVar,
                accVar,
                parentIsDictionary: false,
                rawVar: null,
                throwOnFailure,
                pathPrefix,
                iVar
            );
        }
    }

    private static void AppendScalarElementParse(
        StringBuilder sb,
        PropertyModel property,
        ElementBindingModel element,
        string rawValueVar,
        string parsedVar,
        string accVar,
        bool parentIsDictionary,
        string? rawVar,
        bool throwOnFailure,
        string pathPrefix,
        string iVar
    )
    {
        var elemTypeFqn = element.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var parseCall = GetParseCall(element.Kind, rawValueVar, parsedVar, elemTypeFqn);
        sb.Append("            if (!").Append(parseCall).AppendLine(")");
        sb.AppendLine("            {");
        if (throwOnFailure)
        {
            AppendCollectionElementConversionExceptionThrow(sb, pathPrefix, iVar, property);
        }
        else
        {
            sb.AppendLine("                return false;");
        }
        sb.AppendLine("            }");
        if (parentIsDictionary)
        {
            sb.Append("            ")
                .Append(accVar)
                .AppendLine("[" + rawVar + "!] = " + parsedVar + ";");
        }
        else
        {
            sb.Append("            ").Append(accVar).AppendLine(".Add(" + parsedVar + ");");
        }
    }

    /// <summary>
    /// Fully-qualified accumulator type for a collection <paramref name="element"/>:
    /// arrays accumulate into <c>List&lt;T&gt;</c> (converted back via
    /// <c>ToArray()</c>), read-only collection interfaces into <c>List&lt;T&gt;</c>,
    /// and concrete collection types are used as-is.
    /// </summary>
    private static string GetAccumulatorTypeFqn(ElementBindingModel element)
    {
        if (element.Kind == ScalarKind.Collection_Array && element.Element is { } arrElem)
        {
            var arrElemFqn = arrElem.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return "global::System.Collections.Generic.List<" + arrElemFqn + ">";
        }

        if (
            element.Kind == ScalarKind.Collection_List
            && element.Type is INamedTypeSymbol { TypeKind: TypeKind.Interface }
            && element.Element is { } ifaceElem
        )
        {
            var ifaceElemFqn = ifaceElem.Type.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat
            );
            return "global::System.Collections.Generic.List<" + ifaceElemFqn + ">";
        }

        return element.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static void AppendCollectionBindProperty(
        StringBuilder sb,
        PropertyModel property,
        bool throwOnFailure
    )
    {
        AppendCollectionBindingCore(
            sb,
            property,
            throwOnFailure,
            assignmentLeft: "instance." + property.Name,
            emitAnyVar: !throwOnFailure,
            valueTypeDeclaration: null,
            appendTrailingLine: false
        );
    }

    private static void AppendCollectionInlineValue(
        StringBuilder sb,
        PropertyModel property,
        bool hasAnyVar,
        bool throwOnFailure
    )
    {
        AppendCollectionBindingCore(
            sb,
            property,
            throwOnFailure,
            assignmentLeft: "__value_" + property.Name,
            emitAnyVar: hasAnyVar,
            valueTypeDeclaration: property.Type.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat
            ),
            appendTrailingLine: true
        );
    }

    private static void AppendParseBlock(
        StringBuilder sb,
        PropertyModel property,
        string rawName,
        string valueName,
        string pathName,
        string targetDisplay,
        string memberDisplay,
        bool throwOnFailure,
        string indent
    )
    {
        var targetTypeName = property.UnderlyingType.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat
        );
        var parseCall = GetParseCall(property.ScalarKind, rawName, valueName, targetTypeName);

        sb.Append(indent).Append("if (!").Append(parseCall).AppendLine(")");
        sb.Append(indent).AppendLine("{");
        if (throwOnFailure)
        {
            sb.Append(indent)
                .Append("    throw global::PicoCfg.CfgBindRuntime.CreateConversionException(")
                .Append(pathName)
                .Append(", ")
                .Append(targetDisplay)
                .Append(", ")
                .Append(memberDisplay)
                .AppendLine(");");
        }
        else
        {
            sb.Append(indent).AppendLine("    return false;");
        }

        sb.Append(indent).AppendLine("}");
    }

    private static void AppendCollectionElementConversionExceptionThrow(
        StringBuilder sb,
        string pathPrefix,
        string iVar,
        PropertyModel property
    )
    {
        sb.Append("                throw global::PicoCfg.CfgBindRuntime.CreateConversionException(")
            .Append(pathPrefix)
            .Append(" + \":\" + ")
            .Append(iVar)
            .Append(".ToString(global::System.Globalization.CultureInfo.InvariantCulture)")
            .Append(", ")
            .Append(
                SymbolDisplay.FormatLiteral(
                    property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                    true
                )
            )
            .Append(", ")
            .Append(SymbolDisplay.FormatLiteral(property.Name, true))
            .AppendLine(");");
    }

    private static string GetParseCall(
        ScalarKind scalarKind,
        string rawName,
        string valueName,
        string targetTypeName
    ) =>
        scalarKind switch
        {
            ScalarKind.Boolean =>
                $"global::PicoCfg.CfgBindRuntime.TryParseBoolean({rawName}, out var {valueName})",
            ScalarKind.Byte =>
                $"global::PicoCfg.CfgBindRuntime.TryParseByte({rawName}, out var {valueName})",
            ScalarKind.SByte =>
                $"global::PicoCfg.CfgBindRuntime.TryParseSByte({rawName}, out var {valueName})",
            ScalarKind.Int16 =>
                $"global::PicoCfg.CfgBindRuntime.TryParseInt16({rawName}, out var {valueName})",
            ScalarKind.UInt16 =>
                $"global::PicoCfg.CfgBindRuntime.TryParseUInt16({rawName}, out var {valueName})",
            ScalarKind.Int32 =>
                $"global::PicoCfg.CfgBindRuntime.TryParseInt32({rawName}, out var {valueName})",
            ScalarKind.UInt32 =>
                $"global::PicoCfg.CfgBindRuntime.TryParseUInt32({rawName}, out var {valueName})",
            ScalarKind.Int64 =>
                $"global::PicoCfg.CfgBindRuntime.TryParseInt64({rawName}, out var {valueName})",
            ScalarKind.UInt64 =>
                $"global::PicoCfg.CfgBindRuntime.TryParseUInt64({rawName}, out var {valueName})",
            ScalarKind.Single =>
                $"global::PicoCfg.CfgBindRuntime.TryParseSingle({rawName}, out var {valueName})",
            ScalarKind.Double =>
                $"global::PicoCfg.CfgBindRuntime.TryParseDouble({rawName}, out var {valueName})",
            ScalarKind.Decimal =>
                $"global::PicoCfg.CfgBindRuntime.TryParseDecimal({rawName}, out var {valueName})",
            ScalarKind.Guid =>
                $"global::PicoCfg.CfgBindRuntime.TryParseGuid({rawName}, out var {valueName})",
            ScalarKind.Enum
                // AOT-safe: delegates to Enum.Parse(typeof(TEnum), ...) + cast (no Enum.TryParse reflection)
                => $"global::PicoCfg.CfgBindRuntime.TryParseEnum<{targetTypeName}>({rawName}, out var {valueName})",
            ScalarKind.DateTime =>
                $"global::PicoCfg.CfgBindRuntime.TryParseDateTime({rawName}, out var {valueName})",
            ScalarKind.DateTimeOffset =>
                $"global::PicoCfg.CfgBindRuntime.TryParseDateTimeOffset({rawName}, out var {valueName})",
            ScalarKind.DateOnly =>
                $"global::PicoCfg.CfgBindRuntime.TryParseDateOnly({rawName}, out var {valueName})",
            ScalarKind.TimeOnly =>
                $"global::PicoCfg.CfgBindRuntime.TryParseTimeOnly({rawName}, out var {valueName})",
            ScalarKind.TimeSpan =>
                $"global::PicoCfg.CfgBindRuntime.TryParseTimeSpan({rawName}, out var {valueName})",
            ScalarKind.Uri =>
                $"global::PicoCfg.CfgBindRuntime.TryParseUri({rawName}, out var {valueName})",
            ScalarKind.Version =>
                $"global::PicoCfg.CfgBindRuntime.TryParseVersion({rawName}, out var {valueName})",
            ScalarKind.BigInteger =>
                $"global::PicoCfg.CfgBindRuntime.TryParseBigInteger({rawName}, out var {valueName})",
            _ => throw new InvalidOperationException($"Unexpected scalar kind '{scalarKind}'."),
        };
}
