<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <PackageId>PicoDI.Abs</PackageId>
    <Description>Abstractions for PicoDI - a lightweight, zero-reflection, AOT-compatible dependency injection container</Description>
    <PackageTags>PicoHex;DI;IoC;AOT;Dependency Injection;Abstractions</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\PicoDI.Gen\PicoDI.Gen.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
      PrivateAssets="all"
    />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="..\PicoDI.Gen\bin\$(Configuration)\netstandard2.0\PicoDI.Gen.dll"
      Pack="true"
      PackagePath="analyzers/dotnet/cs"
      Visible="false"
    />
    <None
      Include="buildTransitive\PicoDI.Abs.props"
      Pack="true"
      PackagePath="buildTransitive\PicoDI.Abs.props"
      Visible="false"
    />
  </ItemGroup>
</Project>
