<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <PackageId>PicoCfg.Abs</PackageId>
    <Description>Abstractions for PicoCfg async-first configuration management.</Description>
    <PackageTags>PicoHex;Configuration;AOT;Configuration Injection;Abstractions</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\PicoCfg.Gen\PicoCfg.Gen.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
      PrivateAssets="all"
    />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="..\PicoCfg.Genin\$(Configuration)
etstandard2.0\PicoCfg.Gen.dll"
      Pack="true"
      PackagePath="analyzers/dotnet/cs"
      Visible="false"
    />
    <None
      Include="buildTransitive\PicoCfg.Abs.props"
      Pack="true"
      PackagePath="buildTransitive\PicoCfg.Abs.props"
      Visible="false"
    />
  </ItemGroup>
</Project>
